apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
  SERVLET_CONTEXT_PATH: "/user"
# MYSQL DB
  DB_SERVER: mysql.mysql
  DB_PORT: "31084"
  DB_USERNAME: root
  DB_PASSWORD: passw0rd
