apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: hjsky1010/user:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: DB_PASSWORD
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: SERVLET_CONTEXT_PATH
